"""add document content

Revision ID: 1a94d418aa98
Revises: f31a2b9c7d40
Create Date: 2026-10-10 04:58:44.593971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a94d418aa98"
down_revision: Union[str, Sequence[str], None] = "f31a2b9c7d40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "content")
    # ### end Alembic commands ###
